services:
  db:
    image: postgres:16.9-bullseye
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: NeverUseMeInProd
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080